question N1 :

In [1]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b=a.tolist()
print(b)
print(type(b))

[[1, 2], [3, 4]]
<class 'list'>


question N2 :

In [2]:
import numpy as np
a=np.array([[5,8,6],[1,3,9],[5,4,7],[1,2,3]])
if len(a)==len(a[0]):
    b=a.reshape(len(a),len(a[0]))
    m=np.trace(b)
    print(m)
else :
    b=a.reshape(len(a),len(a[0]))
    print(b)
    m=np.trace(b)
    print(m)

[[5 8 6]
 [1 3 9]
 [5 4 7]
 [1 2 3]]
15


question N3

In [3]:
import numpy as np
x = np.array( [[1,2],[3,5]])
print("Values bigger than 2 =", x[x>2])

Values bigger than 2 = [3 5]


question N4 :

In [14]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[8,4,1],[11,20,31]])
c=a.reshape(len(a),len(a[0]))
d=b.reshape(len(a),len(a[0]))
val=0
if len(a)==len(b) and len(a[0])==len(b[0]):
    for i in range (len(a)): 
        val=c[i]+d[i]
        print(val,end="")

[9 6 4][15 25 37]

question N5 :

In [5]:
import numpy as np
X = np.array([[20,15,10,5],[12,24,36,1]])
print(X)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[20 15 10  5]
 [12 24 36  1]]
[[  7.5    2.5   -2.5   -7.5 ]
 [ -6.25   5.75  17.75 -17.25]]
